name: sepanta-dev

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
      - nginx
    ports:
      - 80:80
      - 80:80/udp
      - 443:443
      - 443:443/udp
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro"
      - "./fullchain.pem:/etc/nginx/fullchain.pem:ro"
      - "./privkey.pem:/etc/nginx/privkey.pem:ro"

  node:
    image: node
    container_name: sepanta
    user: node
    restart: always
    networks:
      - nginx
    ports:
      - 4433:4433
      - 4433:4433/udp
    working_dir: /home/node
    command: --watch ./node.txt
    volumes:
      - "node:/home/node"
      - "./node.txt:/home/node/node.txt"

networks:
  nginx:
    name: nginx

volumes:
  node:
    name: node
    external: true
