name: win-dev

services:
  node:
    image: node
    user: node
    container_name: node
    entrypoint: /usr/bin/tail -f /dev/null
    network_mode: host
    restart: always
    volumes:
      - home:/home/node

volumes:
  home:
    name: home
