name: win0dev

services:
  node:
    image: node
    user: node
    container_name: node
    restart: always
    network_mode: host
    working_dir: /home/node
    command: --watch ./node.txt
    volumes:
      - "node:/home/node"
      - "./node.txt:/home/node/node.txt"

volumes:
  node:
    name: node
